# Generated by Django 5.1.4 on 2025-08-31 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='converstations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='current_period_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'InACTIVE')], default=('inactive', 'InACTIVE'), max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='stripe_subscription_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
